// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class FallingStarsResources
{
        public const string achievement_2_power_ups = "CgkIna_AnPEbEAIQBw"; // <GPGSID>
        public const string leaderboard_the_ultimate_falling_star_destroyer = "CgkIna_AnPEbEAIQAQ"; // <GPGSID>
        public const string achievement_level_20 = "CgkIna_AnPEbEAIQBQ"; // <GPGSID>
        public const string achievement_4_power_ups = "CgkIna_AnPEbEAIQCQ"; // <GPGSID>
        public const string achievement_level_5 = "CgkIna_AnPEbEAIQAg"; // <GPGSID>
        public const string achievement_level_25 = "CgkIna_AnPEbEAIQBg"; // <GPGSID>
        public const string achievement_level_10 = "CgkIna_AnPEbEAIQAw"; // <GPGSID>
        public const string achievement_3_power_ups = "CgkIna_AnPEbEAIQCA"; // <GPGSID>
        public const string achievement_level_15 = "CgkIna_AnPEbEAIQBA"; // <GPGSID>
        public const string achievement_ultimate_falling_star_destroyer = "CgkIna_AnPEbEAIQCg"; // <GPGSID>

}

